Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  nodes = [
    { name: "vpn-node1", ip: "192.168.50.11" },
    { name: "vpn-node2", ip: "192.168.50.12" },
    { name: "vpn-node3", ip: "192.168.50.13" }
  ]

  nodes.each do |node|
    config.vm.define node[:name] do |n|
      n.vm.hostname = node[:name]
      n.vm.network "private_network", ip: node[:ip]
      n.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
      end
      n.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/playbook.yml"
        ansible.inventory_path = "ansible/inventory.ini"
        ansible.compatibility_mode = "2.0"
      end
    end
  end
end
