options {
    listen-on port 53 { 192.168.50.11; };
    listen-on-v6 port 53 { ::1; };

    directory "/var/named";
    dump-file "/var/named/data/cache_dump.db";
    statistics-file "/var/named/data/named_stats.txt";
    memstatistics-file "/var/named/data/named_mem_stats.txt";

    recursion yes;
    allow-query { any; };

    bindkeys-file "/etc/named.iscdlv.key";
    managed-keys-directory "/var/named/dynamic";
    pid-file "/run/named/named.pid";
    session-keyfile "/run/named/session.key";
};

logging {
    channel default_debug {
        file "data/named.run";
        severity dynamic;
    };
};

// RNDC Control
key "rndc-key" {
    algorithm hmac-md5;
    secret "GrtiE9kz16GK+OKKU/qJvQ==";
};

controls {
    inet 192.168.50.11 allow { 192.168.50.15; 192.168.50.16; } keys { "rndc-key"; };
};

// ZONE TRANSFER WITH TSIG
include "/etc/named.zonetransfer.key";

server 192.168.50.10 {
    keys { "zonetransfer.key"; };
};

// Slave zones - NON-VIEWS (receive full zones via TSIG from master)
zone "dns.lab" {
    type slave;
    masters { 192.168.50.10; };
    file "/var/named/slaves/dns.lab.zone";
};

zone "newdns.lab" {
    type slave;
    masters { 192.168.50.10; };
    file "/var/named/slaves/newdns.lab.zone";
};

zone "ddns.lab" {
    type slave;
    masters { 192.168.50.10; };
    file "/var/named/slaves/ddns.lab.zone";
};

zone "50.168.192.in-addr.arpa" {
    type slave;
    masters { 192.168.50.10; };
    file "/var/named/slaves/dns.lab.rev.zone";
};
