# -*- mode: ruby -*-
# vim: set ft=ruby :
# Configuration for MacBook M1 with VMware Fusion

MACHINES = {
  :master => {
        :box_name => "bento/ubuntu-22.04",
        :ip_addr => '192.168.11.150'
  },
  :slave => {
        :box_name => "bento/ubuntu-22.04",
        :ip_addr => '192.168.11.151'
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          # Приватная сеть с DHCP
          box.vm.network "private_network", type: "dhcp"

          box.vm.provider :vmware_desktop do |vmware|
            vmware.memory = 1024
            vmware.cpus = 2
          end

          box.vm.provision :shell do |s|
             s.inline = 'mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh'
          end

      end
  end
end
