[ipa_server]
ipa-server ansible_host=172.16.1.10 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/ipa-server/vmware_desktop/private_key

[ipa_client]
ldap-client ansible_host=172.16.1.11 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/ldap-client/vmware_desktop/private_key

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
