apiVersion: v1
kind: ConfigMap
metadata:
  name: librespeed-env
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/instance: librespeed
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
