apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.registrySecret.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/instance: librespeed
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"auth\":\"%s\"}}}" .Values.registrySecret.registry (printf "%s:%s" .Values.registrySecret.username .Values.registrySecret.password | b64enc) | b64enc }}
