apiVersion: v1
kind: Secret
metadata:
  name: librespeed-secret
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/instance: librespeed
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
