apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: {{ .Values.namespace }}
  labels:
    app: db
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mysql
      name: mysql
  selector:
    app: db
    instance: mysql

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: {{ .Values.namespace }}
  labels:
    app: db
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      name: mysql
  selector:
    app: db
    instance: mysql