---
- name: Deploy PostgreSQL Database
  hosts: "{{ target | default('db') }}"
  become: true
  roles:
    - common
    - firewall
    - node_exporter
    - fluentd
    - postgresql

- name: Deploy PostgreSQL Standby
  hosts: "{{ target_replica | default('db_replica') }}"
  become: true
  roles:
    - common
    - firewall
    - node_exporter
    - fluentd
    - pg_standby
