---
- name: Deploy Monitoring Stack
  hosts: "{{ target | default('monitoring') }}"
  become: true
  roles:
    - common
    - firewall
    - node_exporter
    - fluentd
    - elasticsearch
    - kibana
    - prometheus
    - alertmanager
    - grafana
