# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.provider "virtualbox" do |v|
    v.memory = "2048"
    v.cpus = 2
  end

  config.vm.define "web" do |web|
    web.vm.network "private_network", ip: "192.168.56.10"
    web.vm.hostname = "web"
  end

  config.vm.define "log" do |log|
    log.vm.network "private_network", ip: "192.168.56.11"
    log.vm.hostname = "log"
    log.vm.provider "virtualbox" do |v|
        v.memory = "4096" # ELK needs more RAM
        v.cpus = 2
    end
  end
end
