# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  # PXE Server VM
  config.vm.define "pxeserver" do |server|
    server.vm.box = "ubuntu/jammy64"
    server.vm.hostname = "pxeserver"
    
    # Private network for PXE boot
    server.vm.network "private_network",
      ip: "192.168.50.10",
      virtualbox__intnet: "pxenet"
    
    # VM resources
    server.vm.provider "virtualbox" do |vb|
      vb.name = "pxeserver"
      vb.memory = "2048"
      vb.cpus = 2
    end
    
    # Ansible provisioning
    server.vm.provision "ansible" do |ansible|
      ansible.playbook = "provision.yml"
      ansible.compatibility_mode = "2.0"
      ansible.verbose = "v"
    end
  end
  
  # PXE Client VM (boots from network)
  config.vm.define "pxeclient", autostart: false do |client|
    client.vm.box = "ubuntu/jammy64"
    client.vm.hostname = "pxeclient"
    
    # Private network for PXE boot
    client.vm.network "private_network",
      type: "dhcp",
      virtualbox__intnet: "pxenet"
    
    # VM resources and boot settings
    client.vm.provider "virtualbox" do |vb|
      vb.name = "pxeclient"
      vb.memory = "2048"
      vb.cpus = 2
      
      # Enable UEFI firmware
      vb.customize ["modifyvm", :id, "--firmware", "efi"]
      
      # Set boot order: network first, then disk
      vb.customize ["modifyvm", :id, "--boot1", "net"]
      vb.customize ["modifyvm", :id, "--boot2", "disk"]
      vb.customize ["modifyvm", :id, "--boot3", "none"]
      vb.customize ["modifyvm", :id, "--boot4", "none"]
      
      # Enable network boot
      vb.customize ["modifyvm", :id, "--nicbootprio1", "1"]
      
      # Create a new disk for installation (20GB)
      unless File.exist?("pxeclient-disk.vdi")
        vb.customize ["createhd", "--filename", "pxeclient-disk.vdi", "--size", 20480]
      end
      vb.customize ["storageattach", :id, "--storagectl", "SCSI", "--port", 0, "--device", 0, "--type", "hdd", "--medium", "pxeclient-disk.vdi"]
    end
    
    # Skip default sync folder
    client.vm.synced_folder ".", "/vagrant", disabled: true
    
    # No provisioning - this VM boots from network
  end
  
end
