---
timezone: "Europe/Moscow"

common_packages:
  - curl
  - wget
  - gnupg
  - ca-certificates
  - apt-transport-https
  - software-properties-common
  - ufw
  - chrony
  - python3-pip
  - python3-psycopg2
  - htop
  - net-tools
  - jq
  - unzip

sysctl_params:
  net.core.somaxconn: 65535
  net.ipv4.tcp_max_syn_backlog: 65535
  fs.file-max: 2097152

system_limits_nofile: 65535
system_limits_nproc: 65535
