# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.hostname = "librespeed"

  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provider "vmware_desktop" do |v|
    v.vmx["memsize"] = "4096"
    v.vmx["numvcpus"] = "4"
    v.gui = false
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "deployment/ansible/playbook.yml"
    ansible.inventory_path = "deployment/ansible/inventory.ini"
    ansible.limit = "all"
    ansible.become = true
    ansible.compatibility_mode = "2.0"
  end
end
