# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.box_check_update = false

  # Общие настройки провайдера
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  # ========== MASTER ==========
  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.50.11"

    master.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/master.yml"
      ansible.become = true
    end
  end

  # ========== REPLICA ==========
  config.vm.define "replica" do |replica|
    replica.vm.hostname = "replica"
    replica.vm.network "private_network", ip: "192.168.50.12"

    replica.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/replica.yml"
      ansible.become = true
    end
  end

  # ========== BARMAN ==========
  config.vm.define "barman" do |barman|
    barman.vm.hostname = "barman"
    barman.vm.network "private_network", ip: "192.168.50.13"

    barman.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/barman.yml"
      ansible.become = true
    end
  end
end
